###
GET  http://127.0.0.1:8000/food/
Accept: application/json

###
POST http://127.0.0.1:8000/food/
Content-Type: application/json

{
  "title": "Veg Tacos",
  "cuisine": "Mexican",
  "category": "veg",
  "price": 200,
  "meal_type": "snacks"
}

###
GET http://127.0.0.1:8000/food/2/
Accept: application/json

###
PUT http://127.0.0.1:8000/food/2/
Content-Type: application/json

{
 "category": "non-veg"
}

###
DELETE http://127.0.0.1:8000/food/2/
