# Generated by Django 5.2.7 on 2026-01-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('cuisine', models.CharField(choices=[('Italian', 'Italian'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Continental', 'Continental'), ('Mediterranean', 'Mediterranean'), ('French', 'French'), ('American', 'American')], default='Indian', max_length=200)),
                ('category', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='veg', max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snacks', 'snacks'), ('dessert', 'dessert'), ('beverages', 'beverages')], default='snacks', max_length=200)),
            ],
        ),
    ]
